{"time":"2025-05-23T13:44:53.7902324+01:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"c:\\Users\\eduar\\MIA\\1year_2semester\\nlp\\consumer-complaint-transformer-classifier\\wandb\\run-20250523_134452-7zzbr5mi\\logs\\debug-core.log"}
{"time":"2025-05-23T13:44:54.2518323+01:00","level":"INFO","msg":"created new stream","id":"7zzbr5mi"}
{"time":"2025-05-23T13:44:54.2518323+01:00","level":"INFO","msg":"stream: started","id":"7zzbr5mi"}
{"time":"2025-05-23T13:44:54.2518323+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"7zzbr5mi"}
{"time":"2025-05-23T13:44:54.2518323+01:00","level":"INFO","msg":"handler: started","stream_id":"7zzbr5mi"}
{"time":"2025-05-23T13:44:54.2523914+01:00","level":"INFO","msg":"sender: started","stream_id":"7zzbr5mi"}
{"time":"2025-05-23T13:44:54.5955532+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-05-23T13:53:16.3188084+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/pt_cel/consumer-complaints-robustness/7zzbr5mi/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:53:25.0851156+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"time":"2025-05-23T13:53:31.8234105+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.3:54852->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
